# Generated by Django 4.1.5 on 2023-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expiring_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
