# Generated by Django 4.1.5 on 2023-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_expiring_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item',
        ),
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='invoices.invoiceitem'),
        ),
    ]
