# Generated by Django 4.1.5 on 2023-03-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoiceitem_user_remove_invoice_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='invoices.invoiceitem'),
        ),
    ]
