# Generated by Django 4.1.5 on 2023-02-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_email_alter_client_telf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='telf',
            new_name='phone',
        ),
    ]
