# Generated by Django 4.1.5 on 2023-02-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
    ]
